// Generated by gencpp from file turtlebot3_gazebo/particle_msg.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_GAZEBO_MESSAGE_PARTICLE_MSG_H
#define TURTLEBOT3_GAZEBO_MESSAGE_PARTICLE_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace turtlebot3_gazebo
{
template <class ContainerAllocator>
struct particle_msg_
{
  typedef particle_msg_<ContainerAllocator> Type;

  particle_msg_()
    : points()
    , another_field(0)  {
    }
  particle_msg_(const ContainerAllocator& _alloc)
    : points(_alloc)
    , another_field(0)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _points_type;
  _points_type points;

   typedef uint8_t _another_field_type;
  _another_field_type another_field;





  typedef boost::shared_ptr< ::turtlebot3_gazebo::particle_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot3_gazebo::particle_msg_<ContainerAllocator> const> ConstPtr;

}; // struct particle_msg_

typedef ::turtlebot3_gazebo::particle_msg_<std::allocator<void> > particle_msg;

typedef boost::shared_ptr< ::turtlebot3_gazebo::particle_msg > particle_msgPtr;
typedef boost::shared_ptr< ::turtlebot3_gazebo::particle_msg const> particle_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot3_gazebo::particle_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot3_gazebo::particle_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot3_gazebo::particle_msg_<ContainerAllocator1> & lhs, const ::turtlebot3_gazebo::particle_msg_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points &&
    lhs.another_field == rhs.another_field;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot3_gazebo::particle_msg_<ContainerAllocator1> & lhs, const ::turtlebot3_gazebo::particle_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot3_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_gazebo::particle_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_gazebo::particle_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_gazebo::particle_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_gazebo::particle_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_gazebo::particle_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_gazebo::particle_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot3_gazebo::particle_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52b7cc5e44032cacb08a65980d276cc0";
  }

  static const char* value(const ::turtlebot3_gazebo::particle_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52b7cc5e44032cacULL;
  static const uint64_t static_value2 = 0xb08a65980d276cc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot3_gazebo::particle_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot3_gazebo/particle_msg";
  }

  static const char* value(const ::turtlebot3_gazebo::particle_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot3_gazebo::particle_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] points\n"
"uint8 another_field\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::turtlebot3_gazebo::particle_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot3_gazebo::particle_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
      stream.next(m.another_field);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct particle_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot3_gazebo::particle_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot3_gazebo::particle_msg_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
    s << indent << "another_field: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.another_field);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT3_GAZEBO_MESSAGE_PARTICLE_MSG_H
